# Makefile Template para novos projetos
# Copie este arquivo para a pasta do seu novo projeto
# e ajuste o caminho abaixo se necessário.

# Se o projeto estiver em lab_exemplo/projeto/, o caminho é ../../scripts/arduino.mk
include ../../scripts/arduino.mk
